### PR TITLE
Fixes #29: Updated Footer as per Requirements

### LINKED ISSUE #29: Design Footer for homepage
#### Design footer for homepage

- Footer should be responsive across Mobile, Tablets and Desktop 
- Footer should be easy like this desktop 👇👇👇
Screenshot from 2023-10-20 14-18-57

and look like this on mobile 👇👇👇
Screenshot from 2023-10-20 14-19-22

NB: Pull from Dev and Raise a PR to Dev

### PR DESCRIPTION
**Pull request by Nishanth019**
## Description (#29 )

This PR addresses issue #29, where the footer needed to be modified according to the provided requirements. The changes made are as follows:

- Updated the footer layout to match the specified structure for both desktop and mobile views.
- Adjusted the styling of text, links, and icons for better visual consistency.

bookhive1
bookhive2

Please review the changes, and let me know if you have any feedback or if there are any additional changes or improvements you'd like to make. I kindly request that the "Hacktoberfest Accepted" label be added to this pull request when you merge.
@yhoungdev

### CODE REVIEW

**Comment by theobiabo** [comment]
Hey @Nishanth019 nice work man

**Review by theobiabo — APPROVED** [review]
Nice one man, dont forget to star the repo

**Comment by Nishanth019** [comment]
Thank you sir @yhoungdev . Can you label my PR with "hactoberfest-accepted" so that it may include in my hactoberfest profile..

**Comment by Nishanth019** [comment]
@yhoungdev  If possible, deploy this repo on Vercel, sir, so that we can check requested pull requests instantly on a live website.

**Comment by theobiabo** [comment]
Alread did man. thanks for your contribution

**Comment by theobiabo** [comment]
> @yhoungdev If possible, deploy this repo on Vercel, sir, so that we can check requested pull requests instantly on a live website.

Yeat, its already on vercel. i will allow deployment for any PR raised

**Pull request merged**
